---
title: "boxcox_analysis"
author: "Nils Wendel Heinrich"
date: "2024-06-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(arrow)
library(MASS)

```

```{r data, include=FALSE}

setwd('/Users/heinrich/Projects/Moonlander_iii_LMM/')

close_fixations <- read_feather("data/Experiment3_CloseFixations.arrow")
distant_fixations <- read_feather("data/Experiment3_DistantFixations.arrow")

# exclude fixations without duration (wrongly flagged fixations)
close_fixations <- close_fixations[close_fixations$fixation_duration >= 0.0125, ]
distant_fixations <- distant_fixations[distant_fixations$fixation_duration >= 0.0125, ]

#eliminating fixations that were definitely outside of game boarders
distant_fixations <- filter(distant_fixations, distance_to_spaceship < 16.63762484977781)

```

```{r box_cox_close_fixDur, include=FALSE}

boxcox(lm(close_fixations$fixation_duration ~ 1))

```
lambda, the estimated value is near to 0, implies log transform.

```{r box_cox_close_dist, include=FALSE}

Lambda <- boxcox(lm(close_fixations$distance_to_spaceship ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is close to 0.5, which implies √(x) transformation.

```{r box_cox_distant_fixDur, include=FALSE}

boxcox(lm(distant_fixations$fixation_duration ~ 1))

```
lambda, the estimated value is near to 0, implies log transform.

```{r box_cox_distant_dist, include=FALSE}

Lambda <- boxcox(lm(distant_fixations$distance_to_spaceship ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is near to -0.5, implies 1/√(x) transformation.

```{r box_cox_distant_distobs, include=FALSE}

Lambda <- boxcox(lm(distant_fixations$Dist_to_closest_obstacles ~ 1))

Lambda$x[which(Lambda$y == max(Lambda$y))]

```
lambda, the estimated value is near to 0, implies log transformation.
